

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RiskAssessment
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class fall_reliefEntities : DbContext
{
    public fall_reliefEntities()
        : base("name=fall_reliefEntities")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<tbl_RiskAss_Assessment> tbl_RiskAss_Assessment { get; set; }

    public virtual DbSet<tbl_RiskAss_Session> tbl_RiskAss_Session { get; set; }

    public virtual DbSet<tbl_RiskAss_Questions> tbl_RiskAss_Questions { get; set; }

    public virtual DbSet<tbl_RiskAss_AssQuestion> tbl_RiskAss_AssQuestion { get; set; }

    public virtual DbSet<tbl_RiskAss_ResponseChoice> tbl_RiskAss_ResponseChoice { get; set; }

    public virtual DbSet<vw_RiskAss_RiskLevel> vw_RiskAss_RiskLevel { get; set; }

    public virtual DbSet<vw_RiskAss_RiskStatement> vw_RiskAss_RiskStatement { get; set; }

    public virtual DbSet<tbl_RiskAss_AssessmentResponse> tbl_RiskAss_AssessmentResponse { get; set; }

    public virtual DbSet<tbl_RiskAss_RiskLevel> tbl_RiskAss_RiskLevel { get; set; }

    public virtual DbSet<tbl_ActionPlan_HomeSafety> tbl_ActionPlan_HomeSafety { get; set; }

    public virtual DbSet<tbl_ActionPlan_RiskStatement> tbl_ActionPlan_RiskStatement { get; set; }

    public virtual DbSet<vw_ActionPlan_HomeSafety> vw_ActionPlan_HomeSafety { get; set; }

    public virtual DbSet<vw_HealthRisk> vw_HealthRisk { get; set; }

    public virtual DbSet<vw_QuestionID_Activity> vw_QuestionID_Activity { get; set; }

    public virtual DbSet<vw_QuestionID_Activity_Steps> vw_QuestionID_Activity_Steps { get; set; }

    public virtual DbSet<vw_ActionPlan_DietSolution> vw_ActionPlan_DietSolution { get; set; }

    public virtual DbSet<vw_ActionPlan_DietSolutionFood> vw_ActionPlan_DietSolutionFood { get; set; }

    public virtual DbSet<vw_ActionPlan_HealthRisks> vw_ActionPlan_HealthRisks { get; set; }

    public virtual DbSet<tbl_ActionPlan_NutrientFood> tbl_ActionPlan_NutrientFood { get; set; }

    public virtual DbSet<tbl_ActionPlan_NutrientKey> tbl_ActionPlan_NutrientKey { get; set; }

    public virtual DbSet<tbl_ActionPlan_RiskNutrition> tbl_ActionPlan_RiskNutrition { get; set; }

}

}

