
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RiskAssessment
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_RiskAss_Assessment
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbl_RiskAss_Assessment()
    {

        this.tbl_RiskAss_AssQuestion = new HashSet<tbl_RiskAss_AssQuestion>();

        this.tbl_RiskAss_Session = new HashSet<tbl_RiskAss_Session>();

        this.tbl_RiskAss_RiskLevel = new HashSet<tbl_RiskAss_RiskLevel>();

    }


    public int AssessmentTypeID { get; set; }

    public string AssessmentType { get; set; }

    public string Description { get; set; }

    public Nullable<bool> IsActive { get; set; }

    public int TotalNoOfQuestions { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbl_RiskAss_AssQuestion> tbl_RiskAss_AssQuestion { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbl_RiskAss_Session> tbl_RiskAss_Session { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbl_RiskAss_RiskLevel> tbl_RiskAss_RiskLevel { get; set; }

}

}
