
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RiskAssessment
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_ActionPlan_NutrientKey
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tbl_ActionPlan_NutrientKey()
    {

        this.tbl_ActionPlan_NutrientFood = new HashSet<tbl_ActionPlan_NutrientFood>();

        this.tbl_ActionPlan_RiskNutrition = new HashSet<tbl_ActionPlan_RiskNutrition>();

    }


    public int ID { get; set; }

    public string Nutrient { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbl_ActionPlan_NutrientFood> tbl_ActionPlan_NutrientFood { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<tbl_ActionPlan_RiskNutrition> tbl_ActionPlan_RiskNutrition { get; set; }

}

}
