
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RiskAssessment
{

using System;
    using System.Collections.Generic;
    
public partial class tbl_ActionPlan_HomeSafety
{

    public int ID { get; set; }

    public int QuestionID { get; set; }

    public string Risk { get; set; }

    public string Action { get; set; }

    public string Location_Room { get; set; }

    public string Who { get; set; }

    public string Status { get; set; }

    public string ImgDir { get; set; }



    public virtual tbl_RiskAss_Questions tbl_RiskAss_Questions { get; set; }

}

}
