
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RiskAssessment
{

using System;
    using System.Collections.Generic;
    
public partial class vw_ActionPlan_DietSolutionFood
{

    public int AssessmentNo { get; set; }

    public string risk { get; set; }

    public string Nutrient { get; set; }

    public string SolutionDesc { get; set; }

    public string FoodDescription { get; set; }

    public string FoodGroupName { get; set; }

    public string imgDir { get; set; }

}

}
