
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RiskAssessment
{

using System;
    using System.Collections.Generic;
    
public partial class vw_HealthRisk
{

    public string UID { get; set; }

    public int AssessmentNo { get; set; }

    public int ID { get; set; }

    public string risk { get; set; }

}

}
