
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RiskAssessment
{

using System;
    using System.Collections.Generic;
    
public partial class vw_QuestionID_Activity
{

    public string UID { get; set; }

    public int AssessmentNo { get; set; }

    public int AssQuestionID { get; set; }

    public string Risk { get; set; }

    public string Response { get; set; }

    public string Exercise_name { get; set; }

    public string Exercise_image_link { get; set; }

    public string Exercise_videos_link { get; set; }

    public string actUID { get; set; }

}

}
