
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RiskAssessment
{

using System;
    using System.Collections.Generic;
    
public partial class vw_RiskAss_RiskLevel
{

    public int AssessmentNo { get; set; }

    public int AssessmentTypeID { get; set; }

    public string AssessmentType { get; set; }

    public Nullable<int> RiskScore { get; set; }

    public string RiskLevel { get; set; }

}

}
