
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace RiskAssessment
{

using System;
    using System.Collections.Generic;
    
public partial class vw_RiskAss_RiskStatement
{

    public int AssessmentNo { get; set; }

    public string AssessmentType { get; set; }

    public string QuestionSection { get; set; }

    public string Risk { get; set; }

    public string Risk_Statement { get; set; }

    public int RiskID { get; set; }

    public Nullable<long> ID { get; set; }

    public string RiskImg { get; set; }

}

}
